
<h3>
Terms and Conditions

Conditions of Use
</h3><br /><span style="font-weight: bold;">Terms and Conditions of Use Agreement
</span><br style="font-weight: bold;" /><span style="font-weight: bold;">PLEASE READ THE TERMS AND CONDITIONS OF USE CAREFULLY BEFORE USING THIS SITE</span>. We maintain this web site as a service to our customers, and by using our site you are agreeing to comply with and be bound by the following terms of use. Please review the following terms and conditions carefully, and check them periodically for changes. If you do not agree to the terms and conditions, you should not review information or obtain goods, services or products from this site.
<br /><br />
   <span style="font-weight: bold;">1. Acceptance of Agreement</span>. You agree to the terms and conditions outlined in this Terms and Conditions of use Agreement (&quot;Agreement&quot;) with respect to our site (the &quot;Site&quot;). This Agreement constitutes the entire and only agreement between us and you, and supersedes all prior or contemporaneous agreements, representations, warranties and understandings with respect to the Site, the content, products or services provided by or through the Site, and the subject matter of this Agreement. This Agreement may be amended by us at any time and from time to time without specific notice to you. The latest Agreement will be posted on the Site, and you should review this Agreement prior to using the Site.
   <br /><br /><span style="font-weight: bold;">2. Copyright.</span> The content, organization, graphics, design, compilation, magnetic translation, digital conversion and other matters related to the Site are protected under applicable copyrights, trademarks, registered trademarks and other proprietary (including but not limited to intellectual property) rights. The copying, redistribution, use or publication by you of any such matters or any part of the Site, except as allowed by Section 4, is strictly prohibited. You do not acquire ownership rights to any content, document or other materials viewed through the Site. The posting of information or materials on the Site does not constitute a waiver of any right in such information and materials.
   <br /><br /><span style="font-weight: bold;">3. Fraud.</span> By becoming a member, you confirm that the information provided in this form is true and that you agree to abide by the Terms and Conditions of use of this site. Please note that your membership can be cancelled without notice if it is determined that false or misleading information has been provided, the Terms and Conditions of use have been violated, or other abuses have occurred as determined by elitelightingni.com in its sole discretion. If membership has been revoked, elightlighting.com” reserves the right to refuse application or readmission to the membership program.
   <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">4. Limited Right to Use</span>. The viewing, printing or downloading of any content, graphic, form or document from the Site grants you only a limited, non-exclusive license for use solely by you for your own personal use and not for republication, distribution, assignment, sub license, sale, preparation of derivative works or other use. No part of any content, form or document may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical, other than for your personal use (but not for resale or redistribution).
   <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">5. Editing, Deleting and Modification.</span> We reserve the right in our sole discretion to edit or delete any documents, information or other content appearing on the Site, including this Agreement, without further notice to users of the Site.
   <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">6. Indemnification.</span> You agree to indemnify, defend and hold us and our partners, attorneys, staff and affiliates (collectively, &quot;Affiliated Parties&quot;) harmless from any liability, loss, claim and expense, including reasonable attorney's fees, related to your violation of this Agreement or use of the Site.
   <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">7. Non-transferable.</span> Your right to use the Site is not transferable. Any password or right given to you to obtain information or documents is not transferable and may only be used by you.
   <br /><br /><span style="font-weight: bold;">8. Disclaimer.</span> THE INFORMATION FROM OR THROUGH THE SITE ARE PROVIDED &quot;AS-IS,&quot; &quot;AS AVAILABLE,&quot; AND ALL WARRANTIES, EXPRESS OR IMPLIED, ARE DISCLAIMED (INCLUDING BUT NOT LIMITED TO THE DISCLAIMER OF ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE). THE INFORMATION AND SERVICES MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. WE AND OUR AFFILIATED PARTIES HAVE NO LIABILITY WHATSOEVER FOR YOUR USE OF ANY INFORMATION OR SERVICE. IN PARTICULAR, BUT NOT AS A LIMITATION, WE AND OUR AFFILIATED PARTIES ARE NOT LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING DAMAGES FOR LOSS OF BUSINESS, LOSS OF PROFITS, LITIGATION, OR THE LIKE), WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE NEGATION OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN US. THIS SITE AND THE INFORMATION WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US THROUGH THE SITE SHALL CREATE ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THIS AGREEMENT.
   <br /><br /><span style="font-weight: bold;">9. Limits.</span> All responsibility or liability for any damages caused by viruses contained within the electronic file containing the form or document is disclaimed. WE WILL NOT BE LIABLE TO YOU FOR ANY INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OF ANY KIND THAT MAY RESULT FROM USE OF OR INABILITY TO USE OUR SITE. Our maximum liability to you under all circumstances will be equal to the purchase price you pay for any goods, services or information.
  <br /><br /><span style="font-weight: bold;">10. Use of Information.</span> We reserve the right, and you authorize us, to the use and assignment of all information regarding Site uses by you and all information provided by you in any manner consistent with our Privacy Policy.<br /><br /><span style="font-weight: bold;">11. Third-Party Services.</span> We allow access to or advertise third-party merchant sites (&quot;Merchants&quot;) from which you may purchase or otherwise obtain certain goods or services. You understand that we do not operate or control the products or services offered by Merchants. Merchants are responsible for all aspects of order processing, fulfilment, billing and customer service. We are not a party to the transactions entered into between you and Merchants. YOU AGREE THAT USE OF SUCH MERCHANTS IS AT YOUR SOLE RISK AND IS WITHOUT WARRANTIES OF ANY KIND BY US, EXPRESSED, IMPLIED OR OTHERWISE INCLUDING WARRANTIES OF TITLE, FITNESS FOR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT UNDER NO CIRCUMSTANCES ARE WE LIABLE FOR ANY DAMAGES ARISING FROM THE TRANSACTIONS BETWEEN YOU AND MERCHANTS OR FOR ANY INFORMATION APPEARING ON MERCHANT SITES OR ANY OTHER SITE LINKED TO OUR SITE.<br /><br style="font-weight: bold;" /><span style="font-weight: bold;">12. Third-Party Merchant Policies.</span> All rules, policies (including privacy policies) and operating procedures of Merchants will apply to you while on such sites. We are not responsible for information provided by you to Merchants. We and the Merchants are independent contractors and neither party has authority to make any representations or commitments on behalf of the other.
  <br /><br /><span style="font-weight: bold;">13. Privacy Policy.</span> Our Privacy as it may change from time to time, is a part of this Agreement.
  <br /><br /><span style="font-weight: bold;">14. Payments.</span> You represent and warrant that if you are purchasing something from us or from our Merchants that (i) any credit card information you supply is true, correct and complete, (i) charges incurred by you will be honoured by your credit card company, and (iii) you will pay the charges incurred by you at the posted prices, including any shipping fees and applicable taxes.
  <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">15. Securities Laws.</span> This Site may include statements concerning our operations, prospects, strategies, financial condition, future economic performance and demand for our products or services, as well as our intentions, plans and objectives that are forward-looking statements. These statements are based upon a number of assumptions and estimates which are subject to significant uncertainties, many of which are beyond our control. When used on our Site, words like &quot;anticipates,&quot; &quot;expects,&quot; &quot;believes,&quot; &quot;estimates,&quot; &quot;seeks,&quot; &quot;plans,&quot; &quot;intends&quot; and similar expressions are intended to identify forward-looking statements designed to fall within securities law safe harbors for forward-looking statements. The Site and the information contained herein does not constitute an offer or a solicitation of an offer for sale of any securities. None of the information contained herein is intended to be, and shall not be deemed to be, incorporated into any of our securities-related filings or documents.
  <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">16. Links to Other Web Sites.</span> The Site contains links to other Web sites. We are not responsible for the content, accuracy or opinions express in such Web sites, and such Web sites are not investigated, monitored or checked for accuracy or completeness by us. Inclusion of any linked Web site on our Site does not imply approval or endorsement of the linked Web site by us. If you decide to leave our Site and access these third-party sites, you do so at your own risk.
  <br /><br style="font-weight: bold;" /><span style="font-weight: bold;">17. Submissions.</span> All suggestions, ideas, notes, concepts and other information you may from time to time send to us (collectively, &quot;Submissions&quot;) shall be deemed and shall remain our sole property and shall not be subject to any obligation of confidence on our part. Without limiting the foregoing, we shall be deemed to own all known and hereafter existing rights of every kind and nature regarding the Submissions and shall be entitled to unrestricted use of the Submissions for any purpose, without compensation to the provider of the Submissions.
<br /><br />18. Return Policy.
  <br /><br /><span style="font-weight: bold;">19. Venue; Applicable Law.</span> YOU AGREE THAT ALL ACTIONS OR PROCEEDINGS ARISING DIRECTLY OR INDIRECTLY OUT OF THIS AGREEMENT, OR YOUR USE OF THE SITE OR ANY SAMPLES OR PRODUCTS OBTAINED BY YOU THROUGH SUCH USE, SHALL BE LITIGATED IN THE CIRCUIT COURT OF COUNTY ANTRIM, NORTHERN IRELAND OR THE UNITED KINGDOM DISTRICT COURT FOR THE DISTRICT OF COUNTY ANTRIM. YOU ARE EXPRESSLY SUBMITTING AND CONSENTING IN ADVANCE TO SUCH JURISDICTION IN ANY ACTION OR PROCEEDING IN ANY OF SUCH COURTS, AND ARE WAIVING ANY CLAIM THAT BALLYMENA, COUNTY ANTRIM THE DISTRICT OF NORTHERN IRELAND AN INCONVENIENT FORUM OR AN IMPROPER FORUM BASED ON LACK OF VENUE. This site is created and controlled by Elite lighting in the County of Antrim, Northern Ireland. As such, the laws of the United Kingdom will govern the terms and conditions contained in this Agreement and elsewhere throughout the Site, without giving effect to any principles of conflicts of laws.
  <br /><br /><span style="font-weight: bold;">20. Lapsed Accounts. </span>In order to keep Elite Lighting membership roster current, if a Member does not access his or her account for a period of 365 days or more, Elite Lighting may, in its sole discretion, terminate such Member's account. Elite Lighting will endeavour to notify  a Member of Elite Lighting intent to terminate such Member's account by notice to such Member's provided email address at least 7 days prior to deactivation. If the Member fails to respond to such email notice with 7 days after the day it is sent by Elite Lighting, such Member's account will be terminated as noted above. Therefore, Elite Lighting strongly recommends that all Members keep their accounts and contact data current and in use. While Elite Lighting desires to prevent active accounts from being terminated prematurely, Elite Lighting has no obligation to maintain accounts that appear to Elite Lighting to have been abandoned. Each Member agrees that failure to access his or her account for 365 days or more conclusively indicates that such Member's account has been abandoned and that the account may therefore be terminated.


  <br /><br /><span style="font-weight: bold;">21. Verify Members.</span> Address Elite Lighting reserves the right to contact a Member via email to verify the accuracy of account information (including the Member's correct name and address) that is needed to provide the Member with the information he or she requested from elitelightingni.com
